# Default initial positions for c3pzero_kinova_gen3's ros2_control fake system

initial_positions:
  gen3_joint_1: 0
  gen3_joint_2: 0
  gen3_joint_3: 0
  gen3_joint_4: 0
  gen3_joint_5: 0
  gen3_joint_6: 0
  gen3_joint_7: 0
  gen3_robotiq_85_left_knuckle_joint: 0
