# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator_controller
    - gripper_controller

  manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gen3_joint_1
      - gen3_joint_2
      - gen3_joint_3
      - gen3_joint_4
      - gen3_joint_5
      - gen3_joint_6
      - gen3_joint_7
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gen3_robotiq_85_left_knuckle_joint