# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - robotiq_gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gen3_joint_1
      - gen3_joint_2
      - gen3_joint_3
      - gen3_joint_4
      - gen3_joint_5
      - gen3_joint_6
      - gen3_joint_7
  robotiq_gripper_controller:
    type: GripperCommand
    joints:
      - gen3_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true
