<?xml version="1.0"?>
<robot name="c300" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="load_robot" params="prefix sim_ignition:=false use_fake_hardware:=false">
    <!-- Import macros for main hardware components -->
    <xacro:include filename="$(find c300_description)/urdf/hokuyo_uam05lp.urdf.xacro" />

    <xacro:if value="${use_fake_hardware or sim_ignition}">
      <!-- ros2 control is only used for simulation -->
      <xacro:include filename="$(find c300_description)/urdf/c300.ros2_control.xacro" />
      <xacro:property name="ros2_control_name" value="IgnitionSystem"/>
      <xacro:c300_ros2_control
        name="${ros2_control_name}"
        use_fake_hardware="${use_fake_hardware}"
        sim_ignition="${sim_ignition}"/>
      <xacro:include filename="$(find c300_description)/urdf/c300_transmission_macro.xacro" />
      <xacro:load_gazebo_base_transmissions/>

      <xacro:include filename="$(find c300_description)/urdf/c300_base.gazebo.xacro" />
    </xacro:if>

    <!-- Define robot constants -->
    <xacro:property name="base_width" value="0.46"/>
    <xacro:property name="base_length" value="0.812"/>
    <xacro:property name="base_height" value="0.28"/>

    <xacro:property name="wheel_radius" value="0.1715"/>
    <xacro:property name="wheel_width" value="0.07"/>
    <xacro:property name="wheel_track" value="0.540"/>

    <xacro:property name="caster_xoff" value="0.65"/>

    <!-- Define some commonly used inertial properties  -->
    <xacro:macro name="box_inertia" params="m w h d">
      <inertial>
        <origin xyz="${-base_length/2 + 0.177} 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <mass value="${m}"/>
        <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
      </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <mass value="${m}"/>
        <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
      </inertial>
    </xacro:macro>
    <xacro:macro name="sphere_inertia" params="m r">
      <inertial>
        <mass value="${m}"/>
        <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
      </inertial>
    </xacro:macro>

    <!-- Robot Base -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="file://$(find c300_description)/urdf/meshes/c300_base_link.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="${-base_length/2 + 0.077} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <!-- Robot Footprint -->
    <link name="base_footprint">
      <xacro:box_inertia m="0" w="0" d="0" h="0"/>
    </link>
    <joint name="base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0.0 0.0 ${-wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
      <link name="${prefix}_link">
        <visual>
          <origin xyz="0 0 0" rpy="${pi/2 + y_reflect * pi/2} 0 0"/>
          <geometry>
            <mesh filename="file://$(find c300_description)/urdf/meshes/wheel_link.dae"/>
        </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
      </link>

      <joint name="${prefix}_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_link"/>
        <origin xyz="0 ${y_reflect*wheel_track/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
      </joint>
    </xacro:macro>

    <xacro:wheel prefix="drivewhl_l" x_reflect="1" y_reflect="1" />

    <xacro:wheel prefix="drivewhl_r" x_reflect="1" y_reflect="-1" />

    <link name="rr_caster">
      <visual>
        <geometry>
          <sphere radius="${(wheel_radius-(base_height/2))}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius-(base_height/2))}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="0.5" r="${(wheel_radius-(base_height/2))}"/>
    </link>

    <joint name="rr_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="rr_caster"/>
      <origin xyz="${-caster_xoff} 0.193 ${-(base_height/2)}" rpy="0 0 0"/>
    </joint>

    <link name="lr_caster">
      <visual>
        <geometry>
          <sphere radius="${(wheel_radius-(base_height/2))}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius-(base_height/2))}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="0.5" r="${(wheel_radius-(base_height/2))}"/>
    </link>

    <joint name="lr_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="lr_caster"/>
      <origin xyz="${-caster_xoff} -0.193 ${-(base_height/2)}" rpy="0 0 0"/>
    </joint>

    <!-- Robot's platform for arm mounting and holding containers/totes -->
    <link name="platform_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find c300_description)/urdf/meshes/platform.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find c300_description)/urdf/meshes/platform.dae"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="15" w="${base_width}" d="${base_length - 0.2}" h="0.05"/>
    </link>

    <joint name="platform_joint" type="fixed">
      <parent link="base_link"/>
      <child link="platform_link"/>
      <origin xyz="-0.2 0 0.3" rpy="0 0 0"/>
    </joint>

    <xacro:hokuyo_uam05lp prefix="base" topic="base_scan" parent_link="base_link">
      <origin xyz="0 0 0.155" rpy="0 0 0" />
    </xacro:hokuyo_uam05lp>

  </xacro:macro>
</robot>
